# |-> WorldEdit (Skript) << # |->> Skript developed by alexisl315 (Lennord)

# |-> This skript plugin allows you to redo and improve the WorldEdit plugin (Java) but in skript !

#  |-> PLUGIN CODE:

on right click on iron door:
	if player has permission "worldedit.*" or "worldedit.openirondoor.bypass":
		toggle event-block
		stop

on right click on iron trapdoor:
	if player has permission "worldedit.*" or "worldedit.openirontrapdoor.bypass":
		toggle event-block
		stop